### ISSUE TITLE
AttributeError: 'Games' object has no attribute '_session'

### ISSUE THREAD

**Issue by Jerry-py** [andrewthederp/Disgames#3]
What happened was at line 20:
[Line 20](https://github.com/andrewthederp/Disgames/blob/cadf5f03194876d62783253e3d50ead60a8ec2e5/disgames/mixins/madlib.py#L20)

What should be fixed is in my fork:
[Fork](https://github.com/Jerry-py/Disgames/blob/main/disgames/mixins/madlib.py)

Full error:
```py
['Traceback (most recent call last):\n', '
File "C:\\Users\\pushe\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\disgames\\mixins\\madlib.py", line 31, in madlib\n    

json = await self.request(min, max)\n', '  



File "C:\\Users\\pushe\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\disgames\\mixins\\madlib.py", line 26, in request\n    

response = self.session.get(self.url, params=params)\n', '  



File "C:\\Users\\pushe\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\disgames\\mixins\\madlib.py", line 20, in session\n    

if not self._session:\n', 

"AttributeError: 'Games' object has no attribute '_session'\n", '\n




File"discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Games' object has no attribute '_session'\n"]
```

**Comment by Jerry-py** [comment]
Resolved in: https://github.com/andrewthederp/Disgames/commit/f437e26c487c82e84ecc76fa8fbaf1916d0ce5c7
